# Generated by Django 4.2.13 on 2024-07-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(upload_to='app\\myapp\\static\\program_images\\'),
        ),
    ]
