# Generated by Django 4.2.13 on 2024-07-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_program_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(upload_to='program_images/'),
        ),
    ]
